CREATE TABLE PRODUCTOS(
	ID_PRODUCTO INT UNIQUE NOT NULL AUTO_INCREMENT,
    ID_CATEGORIA INT NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
    PRECIO DOUBLE NOT NULL,
    IMAGEN VARCHAR(255),
    primary key (ID_PRODUCTO)    
);