CREATE TABLE VENTAS(
	ID_VENTA INT NOT NULL UNIQUE AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    FECHA DATE NOT NULL,
    HORA TIME NOT NULL,
    TOTAL FLOAT NOT NULL,
    PRIMARY KEY (ID_VENTA)
);