CREATE TABLE USUARIOS(
	ID_USUARIO INT NOT NULL UNIQUE AUTO_INCREMENT,
    NOMBRE_USUARIO VARCHAR(255) NOT NULL UNIQUE,
    CONTRASEÑA VARCHAR(511) NOT NULL,
    NIVEL_DE_ACCESO INT NOT NULL,
    PRIMARY KEY (ID_USUARIO)
);
