CREATE TABLE DEVOLUCIONES(
	ID_DEVOLUCION INT NOT NULL UNIQUE AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    ID_USUARIO INT NOT NULL,
    HORA TIME NOT NULL,
    TOTAL FLOAT NOT NULL,
    PRIMARY KEY(ID_DEVOLUCION)
);