CREATE TABLE EGRESOS(
	ID_EGRESO INT NOT NULL UNIQUE AUTO_INCREMENT,
    FECHA DATE NOT NULL,
    MONTO FLOAT NOT NULL,
    CONCEPTO VARCHAR(511) NOT NULL,
    ID_USUARIO INT NOT NULL,
    PRIMARY KEY(ID_EGRESO)
);